_BASE_: "./Base-RCNN-C4.yaml"
MODEL:
  BACKBONE:
    FREEZE_AT: 5
  WEIGHTS: "./myILOD/params/R-50.pkl"
  ROI_HEADS:
    NUM_CLASSES: 20
DATALOADER:
  NUM_WORKERS: 8
DATASETS:
  TRAIN: ('voc[1,15]_train', )
  TEST: ('voc_2007_test', )
SOLVER:
  OPTIM: 'SGD'
  IMS_PER_BATCH: 8
  BASE_LR: 0.01
  STEPS: (12000, 16000)
  MAX_ITER: 18000
  WARMUP_ITERS: 100
TEST:
  EVAL_PERIOD: 1000
OUTPUT_DIR: "./output/freeze[body]voc[1,15]SGD"
SEED: 9999
